"""
One-time script: fetches last 30 days of flight history from OpenSky Network
and writes a .sql file ready to paste in Supabase SQL Editor.
"""

import json
import os
import time
import requests
from datetime import datetime, timezone, timedelta

PLANES = {
    "e0659a": "LV-FVZ",
    "e030cf": "LV-CCO",
    "e06546": "LV-FUF",
    "e0b341": "LV-KMA",
    "e0b058": "LV-KAX",
}

OPENSKY_URL       = "https://opensky-network.org/api/flights/aircraft"
OPENSKY_TOKEN_URL = "https://auth.opensky-network.org/auth/realms/opensky-network/protocol/openid-connect/token"
DELAY_BETWEEN_REQUESTS = 15
OUTPUT_FILE       = "import_history.sql"

# Load credentials from credentials_opensky.json (never committed)
_creds_file = os.path.join(os.path.dirname(__file__), "credentials_opensky.json")
with open(_creds_file) as _f:
    _creds = json.load(_f)
CLIENT_ID     = _creds["clientId"]
CLIENT_SECRET = _creds["clientSecret"]


def get_token():
    resp = requests.post(
        OPENSKY_TOKEN_URL,
        data={
            "grant_type":    "client_credentials",
            "client_id":     CLIENT_ID,
            "client_secret": CLIENT_SECRET,
        },
        timeout=15,
    )
    resp.raise_for_status()
    return resp.json()["access_token"]


def fetch_flights(icao24, begin_ts, end_ts, token):
    # OAuth2 API allows max 2 day-partitions per query.
    # Use 1-day aligned chunks (midnight→midnight) to stay within limit.
    results = []
    end_dt = datetime.fromtimestamp(end_ts, tz=timezone.utc)

    # Align cursor to midnight UTC
    raw_start = datetime.fromtimestamp(begin_ts, tz=timezone.utc)
    cursor = raw_start.replace(hour=0, minute=0, second=0, microsecond=0)

    while cursor < end_dt:
        chunk_end = min(cursor + timedelta(days=1), end_dt)
        try:
            resp = requests.get(
                OPENSKY_URL,
                params={"icao24": icao24, "begin": int(cursor.timestamp()), "end": int(chunk_end.timestamp())},
                headers={"Authorization": f"Bearer {token}"},
                timeout=30,
            )
            if resp.status_code == 200:
                data = resp.json() or []
                if data:
                    print(f"    {cursor.date()} — {len(data)} flights")
                results.extend(data)
            elif resp.status_code == 404:
                pass
            else:
                print(f"    {cursor.date()} — HTTP {resp.status_code}")
        except Exception as e:
            print(f"    {cursor.date()} — error: {e}")
        cursor += timedelta(days=1)
        time.sleep(15)

    return results


def escape(s):
    return s.replace("'", "''")


def main():
    begin = datetime(2025, 10, 1, tzinfo=timezone.utc)
    now   = datetime(2025, 12, 31, tzinfo=timezone.utc)

    print(f"Fetching flights from {begin.strftime('%Y-%m-%d')} to {now.strftime('%Y-%m-%d')}\n")

    print("Authenticating with OpenSky...")
    token = get_token()
    print("Token obtained.\n")

    rows = []

    for i, (icao24, tail) in enumerate(PLANES.items()):
        print(f"[{tail}] fetching...")
        flights = fetch_flights(icao24, begin.timestamp(), now.timestamp(), token)
        print(f"  {len(flights)} flights returned")

        for f in flights:
            callsign = escape((f.get("callsign") or "").strip())

            if f.get("firstSeen"):
                ts  = datetime.fromtimestamp(f["firstSeen"], tz=timezone.utc).isoformat()
                dep = escape(f.get("estDepartureAirport") or "")
                meta = json.dumps({"callsign": callsign, "airport": dep, "source": "opensky-history"})
                rows.append(
                    f"((SELECT id FROM aircraft WHERE icao24 = '{icao24}'), "
                    f"'{ts}', 'TAKEOFF', '{escape(meta)}'::jsonb)"
                )

            if f.get("lastSeen"):
                ts  = datetime.fromtimestamp(f["lastSeen"], tz=timezone.utc).isoformat()
                arr = escape(f.get("estArrivalAirport") or "")
                meta = json.dumps({"callsign": callsign, "airport": arr, "source": "opensky-history"})
                rows.append(
                    f"((SELECT id FROM aircraft WHERE icao24 = '{icao24}'), "
                    f"'{ts}', 'LANDING', '{escape(meta)}'::jsonb)"
                )

        if i < len(PLANES) - 1:
            print(f"  Waiting {DELAY_BETWEEN_REQUESTS}s...")
            time.sleep(DELAY_BETWEEN_REQUESTS)

    if not rows:
        print("\nNo flights found. SQL file not written.")
        return

    with open(OUTPUT_FILE, "w") as f:
        f.write("-- Auto-generated by import_history.py\n")
        f.write("-- Paste this in Supabase SQL Editor\n\n")
        f.write("INSERT INTO events (aircraft_id, ts, type, meta)\nVALUES\n")
        f.write(",\n".join(rows))
        f.write("\nON CONFLICT DO NOTHING;\n")

    print(f"\nDone. {len(rows)} rows written to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
